insert into public.ai_templates (
  slug,
  title_mn,
  title_en,
  category,
  description_mn,
  preview_image_url,
  required_images_min,
  required_images_max,
  prompt,
  negative_prompt,
  default_aspect_ratio,
  output_type,
  requires_admin_review,
  is_active
)
values
(
  'old-photo-restoration',
  'Хуучин зураг сэргээх',
  'Old Photo Restoration',
  'Restoration',
  'Зураас, тоос, бүдгэрэлтийг цэвэрлэж дурсамжийн зургийг байгалийн харагдацтай сэргээнэ.',
  'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80',
  1,
  1,
  $$Restore this old damaged photograph naturally. Preserve the exact identity and facial features of every person. Remove scratches, dust, cracks, stains, fading, and blur. Improve sharpness, contrast, and clarity carefully without making the image look artificial. Keep the original composition, clothing, pose, and historical feeling. Make the result photorealistic, respectful, clean, and print-ready. No text, no logo, no watermark.$$,
  null,
  'A4',
  'both',
  false,
  true
),
(
  'black-white-colorization',
  'Хар цагаан зураг өнгө оруулах',
  'Black and White Colorization',
  'Restoration',
  'Хуучин хар цагаан зургийг өнгө оруулж, тоос зураасыг хамт цэвэрлэнэ.',
  'https://images.unsplash.com/photo-1526413232644-8a40f03cc03b?auto=format&fit=crop&w=900&q=80',
  1,
  1,
  $$Colorize and restore this black and white photograph naturally. Preserve the exact identity, facial features, age, expression, hairstyle, clothing design, pose, and original composition. Add realistic natural colors based on the era, skin tones, clothing, and environment. Remove fading, dust, scratches, and stains while keeping the photo authentic and respectful. Photorealistic, clean, print-ready. No text, no logo, no watermark.$$,
  null,
  'A4',
  'both',
  false,
  true
),
(
  'scratch-damage-removal',
  'Зураас, гэмтэл арилгах',
  'Scratch and Damage Removal',
  'Repair',
  'Нугалаа, цууралт, толбо, гэмтлийг засаж эх зургийн зохиомжийг хадгална.',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  1,
  1,
  $$Repair this damaged photo while keeping the original photo realistic and unchanged in identity. Remove visible scratches, dust, stains, cracks, folds, and damaged marks. Preserve all faces, clothing, pose, background layout, and original composition. Improve clarity and contrast only where needed. Do not create a new person or change the scene. Clean, natural, print-ready result. No text, no logo, no watermark.$$,
  null,
  'A4',
  'both',
  false,
  true
),
(
  'ai-studio-portrait',
  'AI студийн хөрөг',
  'AI Studio Portrait',
  'Portrait',
  'Reference зураг дээр тулгуурлан гэрэл, фон, студийн чанарыг сайжруулсан хөрөг үүсгэнэ.',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',
  1,
  3,
  $$Create a clean realistic studio portrait based on the uploaded person photo. Preserve the exact identity, face shape, eyes, nose, mouth, hairstyle, age, skin tone, and expression. Improve lighting, background, clarity, and professional portrait quality. Use a modern studio background, soft flattering light, natural skin texture, and premium camera look. Do not change the person into someone else. Photorealistic, high-quality, print-ready. No text, no logo, no watermark.$$,
  null,
  '4:5',
  'both',
  true,
  true
),
(
  'product-background-upgrade',
  'Бүтээгдэхүүний фон сайжруулах',
  'Product Photo Background Upgrade',
  'Business',
  'Бүтээгдэхүүний хэлбэр, өнгө, шошгыг хадгалж ecommerce-д тохиромжтой фон үүсгэнэ.',
  'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
  1,
  3,
  $$Improve this product photo for ecommerce. Preserve the exact product shape, color, material, logo, label, proportions, and details. Clean the background and place the product in a premium minimal studio setting with soft shadows, realistic lighting, and high-end ecommerce presentation. Do not distort the product. No fake text. No watermark. Print-ready and web-ready.$$,
  null,
  '1:1',
  'both',
  false,
  true
),
(
  'family-merge-beta',
  'Гэр бүлийн зураг нэгтгэх beta',
  'Family Merge Beta',
  'Family',
  'Тусдаа зургуудыг нэг premium гэр бүлийн хөрөг болгон нэгтгэх beta үйлчилгээ.',
  'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=900&q=80',
  2,
  5,
  $$Preserve the exact identity, facial features, face shape, eye shape, nose, mouth, hairstyle, age, skin tone, expression, pose, and natural proportions of every person. Do not change the person into someone else. Do not over-beautify. Do not change age or ethnicity. Create one realistic family portrait using the uploaded reference photos. Place them together naturally in one believable studio portrait composition with matching lighting, camera angle, perspective, skin tone consistency, and realistic shadows. Output must be photorealistic, clean, high-quality, print-ready, natural, and suitable for premium photo printing. No text, no logo, no watermark.$$,
  null,
  'A3',
  'both',
  true,
  true
),
(
  'couple-cinematic-portrait-beta',
  'Хосын cinematic хөрөг beta',
  'Couple Cinematic Portrait Beta',
  'Gift',
  'Хосын reference зургаас дулаан, cinematic premium хөрөг үүсгэнэ.',
  'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80',
  2,
  4,
  $$Preserve the exact identity, facial features, face shape, eye shape, nose, mouth, hairstyle, age, skin tone, expression, pose, and natural proportions of every person. Do not change the person into someone else. Do not over-beautify. Do not change age or ethnicity. Create a realistic premium couple portrait using the uploaded reference photos. Place them together naturally in a cinematic romantic portrait composition with matching lighting, realistic shadows, and premium camera look. Output must be photorealistic, clean, high-quality, print-ready, natural, and suitable for premium photo printing. No text, no logo, no watermark.$$,
  null,
  '4:5',
  'both',
  true,
  true
),
(
  'kids-storybook-poster-beta',
  'Хүүхдийн storybook poster beta',
  'Kids Storybook Poster Beta',
  'Kids',
  'Хүүхдийн царай төрхийг хадгалсан зөөлөн үлгэрийн poster хэв маяг.',
  'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80',
  1,
  2,
  $$Transform the child into a magical storybook-style portrait while preserving the child's face, identity, expression, hairstyle, and pose. Create a soft dreamy illustrated environment with warm lighting, gentle colors, and premium children's book art style. Keep the child recognizable and natural. No text, no logo, no watermark. Print-ready composition.$$,
  null,
  'A4',
  'both',
  true,
  true
),
(
  'pet-portrait-beta',
  'Амьтны premium хөрөг beta',
  'Pet Portrait Beta',
  'Gift',
  'Тэжээвэр амьтны онцлог, өнгө, зан төрхийг хадгалсан premium хөрөг.',
  'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80',
  1,
  3,
  $$Create a premium pet portrait based on the uploaded pet photo. Preserve the pet's exact breed, face, fur color, markings, eyes, expression, and body shape. Improve lighting and composition. Use a clean studio or elegant artistic background. Do not change the pet into a different animal. High-quality, cute, premium, print-ready. No text, no logo, no watermark.$$,
  null,
  '4:5',
  'both',
  true,
  true
)
on conflict (slug) do update set
  title_mn = excluded.title_mn,
  title_en = excluded.title_en,
  category = excluded.category,
  description_mn = excluded.description_mn,
  preview_image_url = excluded.preview_image_url,
  required_images_min = excluded.required_images_min,
  required_images_max = excluded.required_images_max,
  prompt = excluded.prompt,
  negative_prompt = excluded.negative_prompt,
  default_aspect_ratio = excluded.default_aspect_ratio,
  output_type = excluded.output_type,
  requires_admin_review = excluded.requires_admin_review,
  is_active = excluded.is_active,
  updated_at = now();
